import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/lib/utils";
import {
  geistMono,
  geistSans,
  oxaniumHeading,
  publicSansHeading,
  raleway
} from "../fonts";

import {
  SmoothScrollProvider,
  ThemeProvider,
  CursorProvider,
  TooltipProvider,
} from "@/components/globals/providers";
import { Toaster } from "@/components/ui/toast";
import { Footer } from "@/components/globals/Footer"
import { Navbar } from "@/components/globals/Navbar"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, oxaniumHeading.variable, "font-sans", raleway.variable, publicSansHeading.variable)}
    >
      <body
        suppressHydrationWarning
        suppressContentEditableWarning
        className="min-h-full flex flex-col"
      >
        <SmoothScrollProvider>
          <ThemeProvider attribute="class" enableSystem={false}>
            <CursorProvider>
              <TooltipProvider>
                <div className="bg-background text-foreground">
                <Navbar />
                {children}
                <Footer />
                </div>
                <Toaster />
              </TooltipProvider>
            </CursorProvider>
          </ThemeProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
