import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/lib/utils";
import {
  geistMono,
  geistSans,
  oxaniumHeading,
  publicSansHeading,
  raleway
} from "../fonts";

import {
  ThemeProvider,
  CursorProvider,
  TooltipProvider,
} from "@/components/globals/providers";
import { Toaster } from "@/components/ui/toast";
import { MenuProvider } from "@/context/MenuContext";
import { SmoothScroll } from "@/components/SmoothScroll";
import { MenuLayout } from "@/components/MenuLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, oxaniumHeading.variable, "font-sans", raleway.variable, publicSansHeading.variable)}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var isHome = window.location.pathname === '/';
                  if (isHome) {
                    document.documentElement.classList.add('hide-nav-initially');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        suppressHydrationWarning
        suppressContentEditableWarning
        className="min-h-full flex flex-col bg-zinc-950 text-zinc-100 selection:bg-violet-500 selection:text-white"
      >
        <MenuProvider>
          <SmoothScroll>
            <ThemeProvider attribute="class" enableSystem={false}>
              <CursorProvider>
                <TooltipProvider>
                  <MenuLayout>{children}</MenuLayout>
                  <Toaster />
                </TooltipProvider>
              </CursorProvider>
            </ThemeProvider>
          </SmoothScroll>
        </MenuProvider>
      </body>
    </html>
  );
}
